---
deviceType: SIMULATOR
capabilities:
    app: QAR2_v6.1.3(f9bf926).app
    automationName: XCUITest
    platformName: iOS
    platformVersion: 12.1
    deviceName: iPad (5th generation)
    newCommandTimeout: 180
    browserName: ""
    noReset: false
---
deviceType: REAL_DEVICE
capabilities:
    app: kobiton-store:35437
    automationName: XCUITest
    platformName: iOS
    platformVersion: 11.4.1
    newCommandTimeout: 180
    browserName: ""
    deviceGroup: KOBITON
    deviceName: iPad Air 2 (Wi-Fi)
    deviceId: 82770
    captureScreenshots: true